"""1

Revision ID: 92f372ee1164
Revises: 
Create Date: 2026-02-16 19:03:55.537863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f372ee1164'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('hostname')
    )
    op.create_table('jobs',
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('selector', sa.JSON(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL', name='job_status'), nullable=False),
    sa.Column('command_type', sa.Enum('PING', 'RESTART_SERVICE', 'DEPLOY', 'RUN_SCRIPT', name='job_command_type'), nullable=False),
    sa.Column('approval_state', sa.Enum('WAIT_APPROVAL', 'APPROVED', 'REJECTED', name='job_approval_state'), nullable=True),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('signature')
    )
    op.create_table('outbox_event',
    sa.Column('event_type', sa.Enum('PLAN_JOB', name='outbox_event_type'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'SENT', 'FAILED', name='outbox_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('executions',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', 'TIMEOUT', 'BLOCKED', name='executions_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('host_command_blocks',
    sa.Column('host_id', sa.Uuid(), nullable=False),
    sa.Column('command_type', sa.Enum('PING', 'RESTART_SERVICE', 'DEPLOY', 'RUN_SCRIPT', name='host_block_command_type'), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('execution_logs',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('line', sa.Text(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execution_logs')
    op.drop_table('host_command_blocks')
    op.drop_table('executions')
    op.drop_table('outbox_event')
    op.drop_table('jobs')
    op.drop_table('hosts')
    # ### end Alembic commands ###
